// Filesystem store for creative-mode edited worlds: one JSON file per zone id
// under EDITING_DIR. The file CONTENTS are the raw zone JSON itself (same schema
// as a shipped data/<id>.json), so an editor's file can be copied straight back
// into the game's data/ dir to ship the edit.
//
// Kept deliberately separate from the SQLite db (db.js): worlds are large,
// inspectable, and version-controllable as plain files — a row in a blob column
// would be none of those. EDITING_DIR persists across deploys (it lives under
// the app dir but isn't a synced path — same treatment as data.db).

import { mkdirSync, readFileSync, writeFileSync, rmSync, readdirSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));

export function editingDir(env = process.env) {
  return env.EDITING_DIR || join(HERE, "editing");
}

// Zone ids are integers (interiors generated by the editor can be negative), so
// a strict numeric pattern both validates and makes path traversal impossible —
// no slashes, dots, or separators survive. Throws a tagged error the route maps
// to 400.
export function safeId(id) {
  const s = String(id);
  if (!/^-?\d+$/.test(s)) {
    throw Object.assign(new Error(`invalid zone id: ${s}`), { code: "BAD_ID" });
  }
  return s;
}

function fileFor(id, env) {
  return join(editingDir(env), `${safeId(id)}.json`);
}

// Parsed raw zone JSON for `id`, or null when nothing is stored. A corrupt file
// resolves to null (treated as absent) rather than throwing.
export function getEdited(id, env = process.env) {
  const file = fileFor(id, env);
  if (!existsSync(file)) return null;
  try {
    return JSON.parse(readFileSync(file, "utf8"));
  } catch {
    return null;
  }
}

// Write the raw zone JSON for `id`. Pretty-printed so the files stay diffable
// and copy-pasteable into data/.
export function putEdited(id, raw, env = process.env) {
  const file = fileFor(id, env);
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, JSON.stringify(raw, null, 2) + "\n", "utf8");
}

export function deleteEdited(id, env = process.env) {
  rmSync(fileFor(id, env), { force: true });
}

// Ids of all stored worlds (filenames sans .json) — for a future editor sidebar.
export function listEdited(env = process.env) {
  const dir = editingDir(env);
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((f) => f.endsWith(".json"))
    .map((f) => f.slice(0, -".json".length));
}
